const facts = [
  "Dogs have sweat glands in between their paws.",
  "Dalmatians are completely white at birth.",
  "A puppy is born blind, deaf, and toothless.",
  "The Basenji is the worlds only barkless dog.",
  "There is a dog-shaped building in New Zealand.",
  "France has the 2nd highest dog population.",
  "Basset Hounds cannot swim.",
  "The bible mentions dogs 14 times.",
  "Obesity is the #1 health problem among dogs.",
  "Dogs have no sense of time.",
  "The worlds smallest dog breed is the Chihuahua.",
  "The St. Bernard is the heaviest dog breed.",
  "Only dogs and humans have prostates.",
  "Dogs do not have an appendix.",
  "There are 703 breeds of purebred dogs.",
  "Dachshunds were originally bred for fighting badgers.",
  "Smaller breeds mature faster than larger breeds.",
  "Dogs are all direct descendants of wolves.",
  "A dogs pregnancy lasts for approximately 60 days.",
  "Dalmatian puppies are born completely white.",
  "Davy Crockett had a dog named Sport.",
  "Dogs were first domesticated by cavemen.",
  "Dogs live an average of 15 years.",
  "Dogs are natural pack animals.",
  "The process of birthing puppies is called \"whelping.\"",
  "The French Bulldog is incapable of reproducing naturally.",
  "The are 4 constellations named after dogs.",
  "Dogs can learn more than 1000 words.",
  "Perky-eared dogs hear sounds better than floppy-eared dogs.",
  "There are hundreds of breeds of dogs.",
  "The average dog lives 10 to 14 years.",
  "Dogs can see best at dawn and dusk.",
  "Dogs sweat through the pads of their feet.",
  "Petting a dog can lower your blood pressure.",
  "The Basenji is the only barkless dog.",
  "Dogs are direct descendants of wolves.",
  "Puppies are blind, deaf and toothless when born.",
  "A dog's whiskers are used as sensing devices.",
  "A dog's average body temperature is 101.2 degrees.",
  "Obesity is the top health problem among dogs.",
  "Dachshunds were originally bred to fight badgers.",
  "Male dogs have a bone in their penis.",
  "Most dogs have 42 teeth.",
  "Corgi is Welsh for \"dwarf dog\".",
  "Dogs are all direct descendants of wolves."
]
const getRamdomFact = () => {
    return facts[Math.floor(Math.random() * facts.length)];
};

module.exports = {
  getRamdomFact,
};